### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pkg_resources==0.0.0 (from versions: none)

### ISSUE THREAD

**Issue by KayeJin** [cassiersg/ASCAD-5minutes#1]
-   When I configure the python virtual environment, it report that **"ERROR: Could not find a version that satisfies the requirement pkg_resources==0.0.0 (from versions: none)"**. 

 And following [pkg-resources==0.0.0](https://code-specialist.com/python/pkg-resources), if you use ```pip freeze > requirements.txt``` to write the pip freeze's output requirements to a file, it will lead a library bug _since Python 3.3_ . The website suggest that it is better to tell maintainer to switch from virtualenv to venv.

-   And another question is that **numpy 1.19.5**  is not available for _python 3.10_ (the recent one) . So it will report **"ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects"**

Maybe the simplest solution is to fix the Python version rather to install the recent version :D.

**Comment by cassiersg** [comment]
Thanks for the bug report and sorry for the late reply.
